services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nova-it-server
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8050:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nova-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nova-it-client
    ports:
      - "3050:3000"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:8050
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nova-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

networks:
  nova-network:
    driver: bridge
    name: nova-it-network

volumes:
  server_data:
    driver: local
    name: nova-it-server-data